### ISSUE TITLE
A little suggestion, evil until bracket not included? 

### ISSUE THREAD

**Issue by ReneFroger** [noctuid/evil-textobj-anyblock#3]
With the following configuration: 

```
(define-key evil-inner-text-objects-map "b" 'evil-textobj-anyblock-inner-block)
(define-key evil-outer-text-objects-map "b" 'evil-textobj-anyblock-a-block)
```

For example, `cib` stands for **C**hange **I**n the **B**racket. 

But I noticed that `ctb`, alias **c**hange uni**t**l **b**racket don't exist yet in `evil-textobj-anyblock`? Or am I mistaken?

**Comment by noctuid** [comment]
`ctb` is supposed to change until a "b" character though. I don't think evil supports `ct<text-object>`; t after c is bound to `evil-find-char-to`. I don't think vim supports this syntax either?

It may be possible to rebind t so that it will call `evil-find-char-to` unless "b" (or whatever) is input. I'm not sure that it would be such a good idea to do so though. Is `ctb` something you want to do often?

A better idea might be to define something directly after `c` to do this instead (like `cw`). I could add something like that to be mapped in `evil-motion-state-map` so that it would work after `c`, `d`, `y`, etc. Does that sound okay?

**Comment by ReneFroger** [comment]
You're right. `t` is for finding until, the same as `f`-key, I was wrong. Sorry for any inconvience.

Your option about rebinding `t` that will call `evil-find-char-to unless` "b" (or which value text-object-map is given) is input, sounds really good!

The another option seems vaguely to me yet, so I don't know what to say about it. But the first option sounded really good. :+1:.

**Comment by ReneFroger** [comment]
I was wondering if I have described my issue clear enough? My English proficiency is not very well.

**Comment by noctuid** [comment]
Yes, I believe I understand. I will add motions tomorrow and give an example of how to override and rebind `t` (assuming it's as simple as I think).

**Comment by noctuid** [comment]
You can now do something like this:

```
(define-key evil-motion-state-map "b" 'evil-textobj-anyblock-forward-open-block-start)
```

This will allow using `db`, `yb`, etc.

If you want to use `dtb`, you can put this in your init:

```
(evil-define-motion my-evil-motion-t (count char)
  "Move before the next COUNT'th occurrence of CHAR."
  :jump t
  :type inclusive
  (interactive "<c><C>")
  (if (= char (string-to-char "b"))
      (evil-textobj-anyblock-forward-open-block-start count)
    (unwind-protect
        (progn
          (evil-find-char count char)
          (if (> (or count 1) 0)
              (backward-char)
            (forward-char)))
      (setcar evil-last-find #'evil-find-char-to))))

(define-key evil-motion-state-map "t" 'my-evil-motion-t)
```

That is just the normal definition of `evil-find-char-to` except it will call anyblock if `b` is pressed. Let me know if you have any problems.

**Comment by ReneFroger** [comment]
Thanks for your reply, it worked like a charm! Thanks for the support, I really appreciate it.

**Comment by noctuid** [comment]
No problem. Feel free to make another issue if you encounter any problems.
