### ISSUE TITLE
lines-at-a-time object/motion?

### ISSUE THREAD

**Issue by blaenk** [noctuid/evil-textobj-anyblock#5]
Can't think of how to title this. Imagine this:

``` js
  connectToSlack(opts) {
      this.webClient = new slack.WebClient(opts.token);
      this.rtm = new slack.RtmClient(this.webClient, {logLevel: 'debug'});
      this.rtm.start();
      return Bluebird.resolve(this.rtm);
  }
```

I would love it if there were a way to select the contents of this block as if I had done `V` to select, i.e. lines-at-a-time, so only this is selected:

![screenshot](http://i.imgur.com/Te5wgaZ.png)

``` js
      this.webClient = new slack.WebClient(opts.token);
      this.rtm = new slack.RtmClient(this.webClient, {logLevel: 'debug'});
      this.rtm.start();
      return Bluebird.resolve(this.rtm);
```

Of course, if I currently do `vib`, it ends up selecting the part right after the opening brace and right before the closing brace as well.

![screenshot](http://i.imgur.com/9XUmkyk.png)

I think this would be similar to the indent-object packages I've seen, but I think yours is more appropriate/general since it would work regardless of the indentation. Perhaps if there were a `B` object (analogous to `V`) so you could do something like `viB`. It would be best if we could do `Vib` and have it do what I mean, since I already associate `V` with lines-at-a-time, but I'm not sure if that's possible within evil's api.

**Comment by blaenk** [comment]
By the way, I just remembered that other things in vim seem to obey `V`, for example if you do `V` and then `/search`, it will still select lines at a time, whereas this `b` textobject "breaks" out of lines-at-a-time "mode."

**Comment by noctuid** [comment]
This is mostly due to inconsistencies between evil and vim. For example, `Vi{` in vim would select what you want and stay in visual line mode, but in evil, `Vi{` will result in your unwanted example selection. I'm not sure if this is intended; it kind of seems like a bug in evil to me. Another difference is that in vim `vi{` will not select right after a `{` followed by the end of line or right before a `}` preceded by the beginning of line. This is really more of an issue you have with evil, since in your example, anyblock pretty much ends up doing `i{`. I don't know if the evil authors intended on this difference, but it might be a better idea to file an issue on the evil repo asking for a change in this behavior (maybe as an option).

I could maybe add a hacky way to do this by reducing the selection as a last step if only whitespace on the first and last lines would be selected. I'm reluctant to do this though since it wouldn't fix `Vi{` and wouldn't prevent evil from breaking out of the visual line state (it would just be faking it). Also, I don't know of a way to distinguish between the various visual states, so I don't think I could have `Vib` work automatically. It would probably have to be bound to a different key (e.g. `viB` like you suggest).

**Comment by blaenk** [comment]
> This is mostly due to inconsistencies between evil and vim. For example, Vi{ in vim would select what you want and stay in visual line mode, but in evil, Vi{ will result in your unwanted example selection.

Wow you're right, I don't think I ever noticed that! Now I miss something I never had!

> I don't know if the evil authors intended on this difference, but it might be a better idea to file an issue on the evil repo asking for a change in this behavior (maybe as an option).

Sure, thanks for letting me know, I wasn't aware it was an evil thing.

While it would be nice to have at all, I agree with your reasoning that it would probably be best to be fixed on evil's end. I have a feeling that's unlikely to happen (I get the impression the author is bogged down as it is), but it's worth a shot. I just worry I won't be able to articulate it as well as you seem to understand the situation. I'll link the issue back here in case you're interested in checking it out.

Thanks for your prompt response and analysis of the situation.

**Comment by blaenk** [comment]
[Here](https://bitbucket.org/lyro/evil/issues/607/linewise-visual-on-inner-object-breaks-out)'s the issue. Please chime in if I missed anything!

**Comment by noctuid** [comment]
Your explanation made sense to me. I'm not too familiar with the evil internals or how easy it would be to fix this, but I hope someone gets around to it too. It looks like it could be a pretty useful behavior for quite a few situations.

**Comment by noctuid** [comment]
@blaenk I'm reopening this until I've tested the new changes to evil and confirmed they work here.

**Comment by blaenk** [comment]
I tried it out and it does work for `Vi}` now, but not with `Vib`, even though the solution seems to have been a general one (supposedly applies to any text object).

**Comment by noctuid** [comment]
@blaenk Could you please try reloading/recompiling anyblock. It is working for me.

Also, would you mind if I used your example pictures in the README? Thanks for making this issue. I'd ever thought of doing something like this, but I imagine I'll be using this feature myself.

**Comment by noctuid** [comment]
@blaenk Could you please try reloading/recompiling anyblock. It is working for me.

Also, would you mind if I used your example pictures in the README? Thanks for making this issue. I'd never thought of doing something like this, but I imagine I'll be using this feature myself.

**Comment by blaenk** [comment]
You're right it does work for me after recompiling. Not sure why I had to do that since there hasn't been any change in this package, but it works!

And sure, go for it! Feel free to close now too.
